name: build-website
on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.ACTIONS_TOKEN }}
            - uses: oven-sh/setup-bun@v1
            - run: bun install
            - run: bun prettier . --write
            - run: bun run build
            - uses: EndBug/add-and-commit@v9
              if: ${{ github.event.head_commit.message }} != 'Build that commit'
              with:
                  add: '*'
                  message: 'Build that commit'
                  author_email: 'cgsteck@outlook.com'
                  github_token: ${{ secrets.ACTIONS_TOKEN }}
